plugins:
  - babel
  - jest
env:
  node: true
  jest: true
globals:
  window: true
  console: true
parser: babel-eslint
extends:
  - 'airbnb-base'
  - 'plugin:vue/essential'
  - 'plugin:jest/recommended'
rules:
  no-console: off
